### ISSUE TITLE
Python: Silent crash which is not present on upstream DXCam

### ISSUE THREAD

**Issue by cryo-es** [Fidelxyz/DXCam-CPP#4]
This crash occurs when `get_latest_frame()` or `grab()` are called, if Overwatch is in-focus. This does not occur with the upstream (original Python implementation of) DXCam. The Python interpreter exits without providing any crash information, the only thing I can find is this in the Windows Event Viewer > Windows Logs > Application:

```
Faulting application name: python.exe, version: 3.12.1150.1013, time stamp: 0x65724223
Faulting module name: dxgi.dll, version: 10.0.19041.3636, time stamp: 0xeeec3b6b
Exception code: 0xc0000005
Fault offset: 0x0000000000046d47
Faulting process id: 0x2938
Faulting application start time: 0x01da4c564a2841b4
Faulting application path: C:\Users\redacted\AppData\Local\Programs\Python\Python312\python.exe
Faulting module path: C:\WINDOWS\SYSTEM32\dxgi.dll
Report Id: 599073aa-0ca5-453b-98a3-6b56d83f8f77
Faulting package full name: 
Faulting package-relative application ID:
```

Steps to reproduce:
Run the following code and tab into Overwatch (or possibly other fullscreen games? no idea). Observe that the program exits without printing FPS.

```python
import time

import dxcam_cpp as dxcam


start_time, fps = time.perf_counter(), 0
cam = dxcam.create()
start = time.perf_counter()
while fps < 10000:
    frame = cam.grab()
    if frame is not None:  # New frame
        fps += 1
end_time = time.perf_counter() - start_time
print(f"FPS: {fps/end_time}")
```

I am more than happy to help debug this if you need me to test anything. This project gives a huge performance increase to my project, but sadly can't be used due to this crash.

**Comment by Fidelxyz** [comment]
Hi,

I've updated a patch to fix this. Hope that may work.

Thank you for your contribution :)

**Comment by cryo-es** [comment]
Thank you so much, I've tested it and can confirm that it's fixed. Love your work!
